name: Build and Push to ECR

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: [self-hosted, docker, linux]

    env:
      AWS_REGION: us-east-1
      ECR_REPO: rtc/tomcat-warimg
      ACCOUNT_ID: ${{ vars.ACCOUNT_ID }}
      IMAGE_TAG: ${{ github.run_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build WAR
        run: mvn clean package -DskipTests

      - name: Verify WAR file
        run: ls -l target

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/github-actions-ercoidc
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
            | docker login \
              --username AWS \
              --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPO:$IMAGE_TAG .

      - name: Tag Docker image
        run: |
          docker tag $ECR_REPO:$IMAGE_TAG \
          $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

      - name: Push Docker image to ECR
        run: |
          docker push \
          $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

      - name: Stop old container (if exists)
        run: |
          docker stop tomcat || true
          docker rm tomcat || true

      - name: Pull latest image from ECR
        run: |
          docker pull \
          $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

      - name: Run container in detached mode
        run: |
          docker run -d \
            --name tomcat \
            -p 8080:8080 \
            $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
